# getting base image from ubuntu
FROM ubuntu
# for  empty image -> FROM scratch.
# maintainer optional
MAINTAINER Sumit <smt1997sharma@gmail.com>
# RUN cmd executed when build for image
RUN apt-get update
# CMD get executed when container created out of image
CMD ["echo","Hello ubuntu container creted from DockerFile..."]

